name: notebook-nglview
dependencies:
- python=3.6
- nomkl
- nglview=1.0
- ipywidgets==7.0.0
- widgetsnbextension==3.0.0
- ipykernel=4.6
- ambertools=17
# - mdtraj # too slow to build
# - mdanalysis # too slow to build

channels:
  - anaconda
  - bioconda
  - http://ambermd.org/downloads/ambertools/conda/
  # - conda-forge
  # - kain88-de
  # - MDAnalysis
  # - omnia
